export interface CreateSalesProductDTO {
  name: string;
  code?: string;
  sku?: string;
  barcode?: string;
  category?: string;
  category_id?: number | null;
  categoryId?: number | null;
  product_type?: string;
  productType?: string;
  unit?: string;
  description?: string;
  is_active?: boolean;
  isActive?: boolean;
  image?: string;
  master_item_id?: number | null;
  masterItemId?: number | null;
  inventory_item_id?: number | null;
  inventoryItemId?: number | null;
  base_price?: number;
  basePrice?: number;
  wholesale_price?: number;
  wholesalePrice?: number;
  retail_price?: number;
  retailPrice?: number;
  special_price?: number;
  specialPrice?: number;
  min_price?: number;
  minPrice?: number;
  allow_price_override?: boolean;
  allowPriceOverride?: boolean;
  allow_below_min_price?: boolean;
  allowBelowMinPrice?: boolean;
  currency?: string;
  price_list_id?: number | null;
  priceListId?: number | null;
  taxable?: boolean;
  tax_type?: string;
  taxType?: string;
  tax_rate?: number;
  taxRate?: number;
  price_includes_tax?: boolean;
  priceIncludesTax?: boolean;
  default_warehouse_id?: number | null;
  defaultWarehouseId?: number | null;
  default_warehouse?: string;
  defaultWarehouse?: string;
  allow_multi_warehouse?: boolean;
  allowMultiWarehouse?: boolean;
  allow_negative_stock?: boolean;
  allowNegativeStock?: boolean;
  reorder_level?: number;
  reorderLevel?: number;
  min_order_qty?: number;
  minOrderQty?: number;
  max_order_qty?: number;
  maxOrderQty?: number;
  track_batches?: boolean;
  trackBatches?: boolean;
  track_serials?: boolean;
  trackSerials?: boolean;
  track_expiry?: boolean;
  trackExpiry?: boolean;
  is_sellable?: boolean;
  isSellable?: boolean;
  allow_discount?: boolean;
  allowDiscount?: boolean;
  max_discount_pct?: number;
  maxDiscountPct?: number;
  allow_credit_sale?: boolean;
  allowCreditSale?: boolean;
  allow_exceed_credit?: boolean;
  allowExceedCredit?: boolean;
}

export interface UpdateSalesProductDTO extends Partial<CreateSalesProductDTO> {
  id?: number | string;
}
