from pathlib import Path
p=Path('/mnt/data/phase4/modules/restaurant/restaurant_api.routes.ts'); s=p.read_text()
# web confirm replace stock block
route=s.index('router.post("/api/web-orders/:id/confirm"')
start=s.index('      // Reduce ingredient stock from product warehouse',route)
end=s.index('      // 4. Update web order status',start)
new='''      // 3. Apply the web-order recipe through the central inventory engine.\n      const webStockMoves = new Map<string, { warehouseId: number; ingredientId: number; qty: number }>();\n      for (const item of items) {\n        const productRes = await client.query("SELECT warehouse_id, track_inventory FROM products WHERE id = $1", [item.product_id]);\n        const product = productRes.rows[0];\n        if (product?.track_inventory === false) continue;\n        let warehouseId = product?.warehouse_id;\n        if (!warehouseId) warehouseId = (await client.query("SELECT id FROM warehouses WHERE (branch_id = $1 AND is_kitchen = 1) OR branch_id = $1 OR is_main = true ORDER BY is_kitchen DESC, is_main DESC LIMIT 1", [webOrder.branch_id])).rows[0]?.id;\n        if (!warehouseId) throw new Error(`لا يوجد مخزن مرتبط بفرع الطلب للصنف #${item.product_id}`);\n        const recipe = await client.query("SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = $1", [item.product_id]);\n        for (const pi of recipe.rows) {\n          const qty = Number(pi.quantity || 0) * Number(item.quantity || 1);\n          if (qty <= 0) continue;\n          const key = `${warehouseId}:${pi.ingredient_id}`;\n          const current = webStockMoves.get(key);\n          if (current) current.qty += qty;\n          else webStockMoves.set(key, { warehouseId: Number(warehouseId), ingredientId: Number(pi.ingredient_id), qty });\n        }\n      }\n      for (const move of webStockMoves.values()) {\n        await moveStock(client, { warehouse_id: move.warehouseId, ingredient_id: move.ingredientId, delta: -move.qty, ref_type: "web_order_sale", ref_id: Number(newOrderId), user: String(userId || "system"), notes: `خصم مقادير طلب ويب رقم ${newOrderId}` });\n        await client.query("INSERT INTO inventory_transactions (warehouse_id, ingredient_id, quantity, type, reference_id, notes) VALUES ($1, $2, $3, 'out', $4, $5)", [move.warehouseId, move.ingredientId, move.qty, newOrderId, `خصم مقادير طلب ويب رقم ${newOrderId}`]);\n      }\n      if (webStockMoves.size > 0) await client.query("UPDATE orders SET is_deducted = 1 WHERE id = $1", [newOrderId]);\n\n'''
s=s[:start]+new+s[end:]
# update order lock + modification id
route=s.index('router.put("/api/orders/:id"')
pos=s.index('const oldOrder = (await client.query("SELECT * FROM orders WHERE id = $1", [id])).rows[0];',route)
s=s[:pos]+s[pos:].replace('const oldOrder = (await client.query("SELECT * FROM orders WHERE id = $1", [id])).rows[0];','const oldOrder = (await client.query("SELECT * FROM orders WHERE id = $1 FOR UPDATE", [id])).rows[0];',1)
marker='''      // Reverse old items if deducted\n'''
idx=s.index(marker,route)
insert='''      const modificationDetails = items.map((i: any) => `${i.name || i.product_id} (x${i.quantity})`).join(', ');\n      const modificationRes = await client.query(\n        "INSERT INTO order_modifications (order_id, type, old_total, new_total, notes, details) VALUES ($1, 'modification', $2, $3, $4, $5) RETURNING id",\n        [id, oldOrder.total, total, notes || "تعديل الطلب", modificationDetails]\n      );\n      const modificationId = Number(modificationRes.rows[0].id);\n\n'''
s=s[:idx]+insert+s[idx:]
# replace update reverse and deduct blocks
start=s.index('      // Reverse old items if deducted',route); end=s.index('      // Delete existing items',start)
new='''      // Reverse the old stock using a unique modification reference.\n      if (oldOrder.is_deducted && branchWarehouse) {\n        const oldItems = (await client.query("SELECT * FROM order_items WHERE order_id = $1", [id])).rows;\n        const moves = new Map<string, number>();\n        for (const item of oldItems) {\n          const recipe = (await client.query("SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = $1", [item.product_id])).rows;\n          for (const pi of recipe) {\n            const qty = Number(pi.quantity || 0) * Number(item.quantity || 1);\n            moves.set(String(pi.ingredient_id), (moves.get(String(pi.ingredient_id)) || 0) + qty);\n          }\n        }\n        for (const [ingredientId, qty] of moves) {\n          await moveStock(client, { warehouse_id: Number(branchWarehouse.id), ingredient_id: Number(ingredientId), delta: qty, ref_type: "pos_order_edit_reverse", ref_id: modificationId, user: String((req as any).user?.id || "system"), notes: `عكس مخزون تعديل أوردر رقم ${id}` });\n          await client.query("INSERT INTO inventory_transactions (warehouse_id, ingredient_id, quantity, type, reference_id, notes) VALUES ($1, $2, $3, 'in', $4, $5)", [branchWarehouse.id, ingredientId, qty, id, `عكس مخزون تعديل أوردر رقم ${id}`]);\n        }\n      }\n\n'''
s=s[:start]+new+s[end:]
start=s.index('      // Deduct new items if deducted',route); end=s.index('      // Update order total and notes',start)
new='''      // Deduct the replacement items with the same modification reference.\n      if (oldOrder.is_deducted && branchWarehouse) {\n        const moves = new Map<string, number>();\n        for (const item of items) {\n          const recipe = (await client.query("SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = $1", [item.id])).rows;\n          for (const pi of recipe) {\n            const qty = Number(pi.quantity || 0) * Number(item.quantity || 1);\n            moves.set(String(pi.ingredient_id), (moves.get(String(pi.ingredient_id)) || 0) + qty);\n          }\n        }\n        for (const [ingredientId, qty] of moves) {\n          await moveStock(client, { warehouse_id: Number(branchWarehouse.id), ingredient_id: Number(ingredientId), delta: -qty, ref_type: "pos_order_edit_apply", ref_id: modificationId, user: String((req as any).user?.id || "system"), notes: `خصم مخزون تعديل أوردر رقم ${id}` });\n          await client.query("INSERT INTO inventory_transactions (warehouse_id, ingredient_id, quantity, type, reference_id, notes) VALUES ($1, $2, $3, 'out', $4, $5)", [branchWarehouse.id, ingredientId, qty, id, `خصم مخزون تعديل أوردر رقم ${id}`]);\n        }\n      }\n\n'''
s=s[:start]+new+s[end:]
# remove duplicate record modification block later
needle='''      // Record modification\n      const details = items.map((i: any) => `${i.name} (x${i.quantity})`).join(', ');\n      await client.query(\n        "INSERT INTO order_modifications (order_id, type, old_total, new_total, notes, details) VALUES ($1, 'modification', $2, $3, $4, $5)",\n        [id, oldOrder.total, total, notes || "تعديل الطلب", details]\n      );\n      \n'''
s=s.replace(needle,'',1)
# add-items lock and central replacement
route=s.index('router.post("/api/orders/:orderId/add-items"')
pos=s.index('const order = (await client.query("SELECT * FROM orders WHERE id = $1", [orderId])).rows[0];',route)
s=s[:pos]+s[pos:].replace('const order = (await client.query("SELECT * FROM orders WHERE id = $1", [orderId])).rows[0];','const order = (await client.query("SELECT * FROM orders WHERE id = $1 FOR UPDATE", [orderId])).rows[0];',1)
# insert modification before items and capture id
idx=s.index('      for (const item of items) {',route)
ins='''      const additionDetails = items.map((i: any) => `${i.name || i.id} (x${i.quantity})`).join(', ');\n      const additionRes = await client.query(\n        "INSERT INTO order_modifications (order_id, type, old_total, new_total, notes, details) VALUES ($1, 'addition', $2, $3, $4, $5) RETURNING id",\n        [orderId, order.total, order.total + Math.max(0, Number(additionalTotal) - Number(additionalDiscount || 0)), notes || "إضافة عناصر", additionDetails]\n      );\n      const additionId = Number(additionRes.rows[0].id);\n\n'''
s=s[:idx]+ins+s[idx:]
start=s.index('      if (order.is_deducted) {',route); end=s.index('      await client.query("COMMIT");',start)
new='''      if (order.is_deducted) {\n        let branchWarehouse = (await client.query("SELECT id FROM warehouses WHERE branch_id = $1 AND is_kitchen = 1 LIMIT 1", [order.branch_id])).rows[0];\n        if (!branchWarehouse) branchWarehouse = (await client.query("SELECT id FROM warehouses WHERE branch_id = $1 LIMIT 1", [order.branch_id])).rows[0];\n        if (!branchWarehouse) throw new Error("لا يوجد مخزن للفرع لتنفيذ الإضافة");\n        const moves = new Map<string, number>();\n        for (const item of items) {\n          const recipe = (await client.query("SELECT ingredient_id, quantity FROM product_ingredients WHERE product_id = $1", [item.id])).rows;\n          for (const pi of recipe) {\n            const qty = Number(pi.quantity || 0) * Number(item.quantity || 1);\n            moves.set(String(pi.ingredient_id), (moves.get(String(pi.ingredient_id)) || 0) + qty);\n          }\n        }\n        for (const [ingredientId, qty] of moves) {\n          await moveStock(client, { warehouse_id: Number(branchWarehouse.id), ingredient_id: Number(ingredientId), delta: -qty, ref_type: "pos_order_add", ref_id: additionId, user: String((req as any).user?.id || "system"), notes: `خصم مقادير إضافية لأوردر رقم ${orderId}` });\n          await client.query("INSERT INTO inventory_transactions (warehouse_id, ingredient_id, quantity, type, reference_id, notes) VALUES ($1, $2, $3, 'out', $4, $5)", [branchWarehouse.id, ingredientId, qty, orderId, `خصم مقادير إضافية لأوردر رقم ${orderId}`]);\n        }\n      }\n      \n'''
s=s[:start]+new+s[end:]
p.write_text(s)
print('patch3 done')
