import React, { useEffect, useState } from "react";
import { Bell, Check, Command, Search, Workflow, BarChart3, Users, Package, UserRound, ClipboardCheck, RefreshCw, Plus, Power, Trash2 } from "lucide-react";
import { api } from "../utils/api";

type SearchResult = { type:string; label:string; id:any; title:string; path:string };
type WorkflowDef = { id:number; name:string; module_type:string; description?:string; steps:any[]; is_active:boolean };

export function EnterpriseHub({ onNavigate }: { onNavigate: (view:any)=>void }) {
  const [q,setQ]=useState(""); const [results,setResults]=useState<SearchResult[]>([]); const [loading,setLoading]=useState(false);
  const [notifications,setNotifications]=useState<any[]>([]); const [metrics,setMetrics]=useState<Record<string,number>>({});
  const [workflows,setWorkflows]=useState<WorkflowDef[]>([]); const [showCreate,setShowCreate]=useState(false);
  const [newWorkflow,setNewWorkflow]=useState({name:"",module_type:"custom",description:"",steps:"خطوة جديدة"});

  const search=async(v:string)=>{setQ(v); if(v.trim().length<2){setResults([]);return;} setLoading(true); try{const r=await api.get(`/api/enterprise/search?q=${encodeURIComponent(v)}`);const body=await r.json();setResults(body.data||body||[]);}catch{}finally{setLoading(false);}};
  const load=async()=>{try{const [n,m,w]=await Promise.all([api.get('/api/enterprise/notifications'),api.get('/api/enterprise/command-center'),api.get('/api/enterprise/workflows')]);const [notificationsBody,metricsBody,workflowsBody]=await Promise.all([n.json(),m.json(),w.json()]);setNotifications(notificationsBody.data||notificationsBody||[]);setMetrics(metricsBody.metrics||{});setWorkflows(workflowsBody.data||workflowsBody||[]);}catch{}};
  useEffect(()=>{load(); const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('enterprise-global-search')?.focus();}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
  const cards=[['customers','العملاء',Users],['products','المنتجات',Package],['employees','الموظفون',UserRound],['approvals','موافقات معلقة',ClipboardCheck]] as const;
  const markRead=(id:number)=>api.put(`/api/enterprise/notifications/${id}/read`,{}).then(load);
  const createWorkflow=async()=>{const steps=newWorkflow.steps.split(',').map(s=>s.trim()).filter(Boolean).map(name=>({name,role:'approver'}));if(!newWorkflow.name.trim()||!steps.length)return;await api.post('/api/enterprise/workflows',{name:newWorkflow.name,module_type:newWorkflow.module_type,description:newWorkflow.description,steps});setNewWorkflow({name:"",module_type:"custom",description:"",steps:"خطوة جديدة"});setShowCreate(false);load();};
  const toggleWorkflow=(w:WorkflowDef)=>api.put(`/api/enterprise/workflows/${w.id}`,{is_active:!w.is_active}).then(load);
  const deleteWorkflow=(id:number)=>{if(confirm('حذف مسار العمل؟'))api.delete(`/api/enterprise/workflows/${id}`).then(load)};
  return <div className="p-4 sm:p-7 space-y-6 max-w-7xl mx-auto" dir="rtl">
    <div className="rounded-3xl bg-slate-900 text-white p-6 shadow-xl"><div className="flex items-center gap-3 mb-4"><Command/><div><h1 className="text-2xl font-black">مركز المؤسسة الذكي</h1><p className="text-slate-300 text-sm">بحث موحد، تنبيهات، مؤشرات تشغيل، ومسارات عمل قابلة للإدارة.</p></div></div>
      <div className="relative"><Search className="absolute right-4 top-3.5 w-5 h-5 text-slate-400"/><input id="enterprise-global-search" value={q} onChange={e=>search(e.target.value)} placeholder="ابحث في العملاء، المنتجات، الموظفين، الموردين، الموافقات..." className="w-full rounded-2xl bg-white text-slate-900 py-3 pr-12 pl-16 outline-none"/><kbd className="absolute left-4 top-2.5 hidden sm:block rounded-lg border bg-slate-100 text-slate-500 px-2 py-1 text-xs">Ctrl K</kbd>{loading&&<RefreshCw className="absolute left-16 top-3.5 animate-spin w-5 h-5"/>}
      {results.length>0&&<div className="absolute z-20 mt-2 w-full bg-white text-slate-800 rounded-2xl shadow-2xl overflow-hidden">{results.map((r,i)=><button key={i} onClick={()=>{setResults([]); if(r.type==='customers')onNavigate('customers'); else if(r.type==='products')onNavigate('products'); else if(r.type==='employees')onNavigate('hr'); else if(r.type==='approval_requests')onNavigate('approvals');}} className="w-full text-right px-4 py-3 hover:bg-slate-50 border-b flex justify-between"><span className="font-bold">{r.title}</span><span className="text-xs text-slate-400">{r.label}</span></button>)}</div>}</div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{cards.map(([k,label,Icon])=><div key={k} className="bg-white rounded-2xl border border-slate-200 p-5 shadow-sm"><Icon className="w-6 h-6 text-blue-600 mb-3"/><div className="text-2xl font-black">{metrics[k]??0}</div><div className="text-sm text-slate-500 font-bold">{label}</div></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-2xl border p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-black flex gap-2 items-center"><Bell/> مركز التنبيهات</h2><button onClick={()=>api.put('/api/enterprise/notifications/read-all',{}).then(load)} className="text-xs text-blue-600 font-bold">تحديد الكل كمقروء</button></div>{notifications.length===0?<p className="text-slate-400 text-sm">لا توجد تنبيهات حالياً.</p>:notifications.slice(0,8).map(n=><div key={n.id} className={`flex gap-3 p-3 border-b last:border-0 ${n.is_read?'opacity-60':''}`}><div className="flex-1"><b>{n.title}</b><p className="text-sm text-slate-500">{n.message}</p></div>{!n.is_read&&<button title="تحديد كمقروء" onClick={()=>markRead(n.id)}><Check className="w-4 h-4 text-emerald-600"/></button>}</div>)}</section>
    <section className="bg-white rounded-2xl border p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-black flex gap-2 items-center"><Workflow/> محرك سير العمل</h2><button onClick={()=>setShowCreate(v=>!v)} className="flex items-center gap-1 text-xs bg-slate-900 text-white rounded-xl px-3 py-2"><Plus className="w-4 h-4"/> مسار جديد</button></div>
      {showCreate&&<div className="mb-4 p-4 rounded-xl border bg-slate-50 space-y-2"><input value={newWorkflow.name} onChange={e=>setNewWorkflow({...newWorkflow,name:e.target.value})} placeholder="اسم المسار" className="w-full rounded-lg border px-3 py-2"/><input value={newWorkflow.module_type} onChange={e=>setNewWorkflow({...newWorkflow,module_type:e.target.value})} placeholder="نوع الموديول" className="w-full rounded-lg border px-3 py-2"/><input value={newWorkflow.steps} onChange={e=>setNewWorkflow({...newWorkflow,steps:e.target.value})} placeholder="الخطوات مفصولة بفاصلة" className="w-full rounded-lg border px-3 py-2"/><button onClick={createWorkflow} className="rounded-lg bg-blue-600 text-white px-4 py-2 text-sm font-bold">حفظ</button></div>}
      <div className="space-y-3">{workflows.map(w=><div key={w.id} className="p-4 rounded-xl bg-slate-50 border"><div className="flex justify-between gap-2"><div><b>{w.name}</b><div className="text-xs text-slate-500">{w.description||w.module_type} · {w.steps?.length||0} خطوات</div></div><div className="flex gap-1"><button title={w.is_active?'تعطيل':'تفعيل'} onClick={()=>toggleWorkflow(w)}><Power className={`w-4 h-4 ${w.is_active?'text-emerald-600':'text-slate-400'}`}/></button><button title="حذف" onClick={()=>deleteWorkflow(w.id)}><Trash2 className="w-4 h-4 text-red-500"/></button></div></div><div className="text-xs text-slate-500 mt-2">{(w.steps||[]).map((s:any)=>s.name).join(' → ')}</div></div>)}</div>
    </section></div>
    <div className="rounded-2xl border bg-white p-5 flex items-center gap-4"><BarChart3 className="text-blue-600"/><div><b>Command Center</b><p className="text-sm text-slate-500">نقطة دخول موحدة للعمليات والبحث والتنبيهات وسير العمل، ومهيأة للتوسع لاحقاً نحو التحليلات التنبؤية وAI.</p></div></div>
  </div>
}
