import React,{useEffect,useMemo,useState} from "react";
import {api} from "../utils/api";
import {Building2,Plus,RefreshCw,Search,Settings,FileText,Printer,Save,X,MapPin,Wallet} from "lucide-react";

type Property={id:number;name:string;property_type:string;address?:string;branch_id?:number|null;owner_name?:string;status:string;monthly_rent:number;purchase_value:number;notes?:string};
const money=(n:number)=>Number(n||0).toLocaleString("ar-EG",{minimumFractionDigits:2,maximumFractionDigits:2});
export const RealEstateManagement:React.FC<{onBack:()=>void;initialTab?:string}>=({onBack,initialTab})=>{
 const normalize=(v?:string)=>v?.startsWith("realestate_")?"settings":v?.startsWith("realestate")?"reports":v&&["leases","expenses","collections","maintenance"].includes(v)?"properties":v||"properties"; const [tab,setTab]=useState(normalize(initialTab)),[items,setItems]=useState<Property[]>([]),[search,setSearch]=useState(""),[loading,setLoading]=useState(false),[show,setShow]=useState(false),[editing,setEditing]=useState<Property|null>(null),[settings,setSettings]=useState<any>({default_currency:"EGP",enable_accounting_link:true,enable_branch_link:true}),[reports,setReports]=useState<any>(null);
 const empty={name:"",property_type:"building",address:"",branch_id:"",owner_name:"",status:"active",monthly_rent:"0",purchase_value:"0",notes:""}; const [form,setForm]=useState<any>(empty);
 const load=async()=>{setLoading(true);try{const r=await api.get("/api/realestate/properties");if(r.ok)setItems(await r.json());}finally{setLoading(false)}};
 const loadReports=async()=>{const r=await api.get("/api/realestate/reports");if(r.ok)setReports(await r.json())}; const loadSettings=async()=>{const r=await api.get("/api/realestate/settings");if(r.ok)setSettings({...settings,...await r.json()})};
 useEffect(()=>{load();loadReports();loadSettings()},[]); useEffect(()=>{if(initialTab)setTab(normalize(initialTab))},[initialTab]);
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.address||""} ${x.owner_name||""}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();const p={...form,branch_id:form.branch_id?Number(form.branch_id):null,monthly_rent:Number(form.monthly_rent||0),purchase_value:Number(form.purchase_value||0)};const r=editing?await api.put(`/api/realestate/properties/${editing.id}`,p):await api.post("/api/realestate/properties",p);if(r.ok){setShow(false);await load();await loadReports() }else alert((await r.json()).error||"تعذر الحفظ")};
 const remove=async(id:number)=>{if(confirm("هل تريد حذف العقار؟")){const r=await api.delete(`/api/realestate/properties/${id}`);if(r.ok){await load();await loadReports()}}};
 const saveSettings=async()=>{const r=await api.put("/api/realestate/settings",settings);if(r.ok)alert("تم حفظ الإعدادات")};
 return <div className="min-h-screen bg-slate-50 p-4 md:p-6"><div className="max-w-7xl mx-auto"><div className="flex items-center justify-between mb-5"><div className="flex items-center gap-3"><button onClick={onBack} className="px-3 py-2 border rounded-xl">رجوع</button><div className="p-3 bg-emerald-100 text-emerald-700 rounded-2xl"><Building2/></div><div><h1 className="text-2xl font-black">إدارة العقارات</h1><p className="text-sm text-slate-500">إدارة الممتلكات وربطها بالفروع والحسابات والتقارير</p></div></div><button onClick={()=>{setEditing(null);setForm(empty);setShow(true)}} className="px-4 py-3 bg-emerald-600 text-white rounded-xl font-black flex gap-2"><Plus/> عقار جديد</button></div>
 <div className="flex gap-2 flex-wrap mb-5"><Tab a={tab==="properties"} c={()=>setTab("properties")} t="العقارات" i={<Building2/>}/><Tab a={tab==="settings"} c={()=>setTab("settings")} t="الإعدادات" i={<Settings/>}/><Tab a={tab==="reports"} c={()=>{setTab("reports");loadReports()}} t="التقارير" i={<FileText/>}/></div>
 {tab==="properties"&&<><div className="bg-white border rounded-2xl p-4 mb-4 flex gap-3"><div className="relative flex-1"><Search className="absolute right-3 top-3.5 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث باسم العقار أو العنوان أو المالك" className="w-full pr-10 p-3 border rounded-xl"/></div><button onClick={load} className="p-3 border rounded-xl"><RefreshCw className={loading?"animate-spin":""}/></button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(p=><div key={p.id} className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><div><h3 className="font-black text-lg">{p.name}</h3><span className="text-xs text-emerald-700 font-bold">{p.status}</span></div><Building2 className="text-emerald-600"/></div><div className="mt-4 space-y-2 text-sm text-slate-600"><div><MapPin className="inline w-4 ml-1"/>{p.address||"بدون عنوان"}</div><div>المالك: <b>{p.owner_name||"—"}</b></div><div>قيمة الشراء: <b>{money(p.purchase_value)}</b></div><div>الإيجار الشهري: <b>{money(p.monthly_rent)}</b></div></div><div className="flex gap-2 mt-4"><button onClick={()=>{setEditing(p);setForm({...p,branch_id:p.branch_id??""});setShow(true)}} className="flex-1 border rounded-xl py-2 font-bold">تعديل</button><button onClick={()=>remove(p.id)} className="px-4 border border-rose-200 text-rose-600 rounded-xl">حذف</button></div></div>)}{!filtered.length&&<div className="col-span-full bg-white border rounded-2xl p-12 text-center text-slate-400 font-bold">لا توجد عقارات</div>}</div></>}
 {tab==="settings"&&<div className="bg-white border rounded-2xl p-6 max-w-3xl"><h2 className="text-xl font-black mb-5">إعدادات العقارات</h2><div className="grid md:grid-cols-2 gap-4"><label className="border rounded-xl p-4"><span className="block text-xs font-bold text-slate-500">العملة الافتراضية</span><input className="mt-2 w-full border rounded-lg p-2" value={settings.default_currency||"EGP"} onChange={e=>setSettings({...settings,default_currency:e.target.value})}/></label><Check label="ربط العقارات بالفروع" value={settings.enable_branch_link} set={(v:boolean)=>setSettings({...settings,enable_branch_link:v})}/><Check label="تفعيل الربط المحاسبي" value={settings.enable_accounting_link} set={(v:boolean)=>setSettings({...settings,enable_accounting_link:v})}/></div><button onClick={saveSettings} className="mt-5 bg-emerald-600 text-white px-5 py-3 rounded-xl font-black flex gap-2"><Save/> حفظ</button></div>}
 {tab==="reports"&&<div><div className="grid md:grid-cols-3 gap-4 mb-4"><K title="العقارات النشطة" v={reports?.summary?.count||0}/><K title="إجمالي قيمة الشراء" v={reports?.summary?.purchase_value||0}/><K title="إجمالي الإيجار الشهري" v={reports?.summary?.monthly_rent||0}/></div><div className="bg-white border rounded-2xl p-5"><div className="flex justify-between"><h2 className="font-black text-lg">تقرير العقارات</h2><button onClick={()=>window.print()} className="border rounded-xl px-3 py-2 flex gap-2"><Printer/> طباعة</button></div><table className="w-full mt-4 text-sm"><thead><tr className="bg-slate-50"><th className="p-3 text-right">العقار</th><th className="p-3">النوع</th><th className="p-3">الحالة</th><th className="p-3">القيمة</th><th className="p-3">الإيجار</th></tr></thead><tbody>{items.map(p=><tr className="border-t" key={p.id}><td className="p-3 font-bold">{p.name}</td><td className="p-3">{p.property_type}</td><td className="p-3">{p.status}</td><td className="p-3">{money(p.purchase_value)}</td><td className="p-3">{money(p.monthly_rent)}</td></tr>)}</tbody></table></div></div>}
 {show&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-2xl max-h-[90vh] overflow-auto"><div className="p-4 border-b flex justify-between"><b>{editing?"تعديل عقار":"إضافة عقار"}</b><button onClick={()=>setShow(false)}><X/></button></div><form onSubmit={save} className="p-5 grid md:grid-cols-2 gap-3">{[["name","اسم العقار"],["property_type","نوع العقار"],["address","العنوان"],["owner_name","المالك/المؤجر"],["monthly_rent","الإيجار الشهري"],["purchase_value","قيمة الشراء"],["branch_id","رقم الفرع"]].map(([k,l])=><label className="text-sm font-bold" key={k}>{l}<input required={k==="name"} className="mt-1 w-full border rounded-lg p-2.5" value={form[k]??""} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label className="text-sm font-bold">الحالة<select className="mt-1 w-full border rounded-lg p-2.5" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">نشط</option><option value="rented">مؤجر</option><option value="vacant">شاغر</option><option value="sold">مباع</option><option value="inactive">موقوف</option></select></label><label className="md:col-span-2 text-sm font-bold">ملاحظات<textarea className="mt-1 w-full border rounded-lg p-2.5" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="md:col-span-2 flex justify-end gap-2"><button type="button" onClick={()=>setShow(false)} className="border px-4 py-2 rounded-xl">إلغاء</button><button className="bg-emerald-600 text-white px-5 py-2 rounded-xl font-bold">حفظ</button></div></form></div></div>}
 </div></div>
};
const Tab=({a,c,t,i}:{a:boolean;c:()=>void;t:string;i:React.ReactNode})=><button onClick={c} className={`px-4 py-2.5 rounded-xl font-black flex gap-2 items-center ${a?"bg-emerald-600 text-white":"bg-white border text-slate-600"}`}>{i}{t}</button>;
const K=({title,v}:{title:string;v:number})=><div className="bg-white border rounded-2xl p-5"><div className="text-xs font-bold text-slate-500">{title}</div><div className="text-2xl font-black mt-2">{money(v)}</div></div>;
const Check=({label,value,set}:{label:string;value:any;set:(v:boolean)=>void})=><label className="border rounded-xl p-4 flex items-center gap-3 font-bold"><input type="checkbox" checked={!!value} onChange={e=>set(e.target.checked)}/>{label}</label>;
