import {
  Bot,
  LayoutGrid,
  UtensilsCrossed,
  Table2,
  ChefHat,
  Users,
  Calendar,
  CalendarDays,
  FileCog,
  Package,
  Truck,
  UserCircle,
  Target,
  ShieldCheck,
  Settings,
  Clock,
  Warehouse,
  ShoppingCart,
  BarChart3,
  Calculator,
  FileText,
  FileSpreadsheet,
  Wallet,
  UserPlus,
  TruckIcon,
  MapPin,
  Trash2,
  Database,
  Printer,
  MessageSquareWarning,
  ShieldAlert,
  Factory,
  Landmark,
  Zap,
  Scale,
  Wrench,
  Activity,
  BookOpen,
  History,
  PieChart,
  FolderTree,
  Lock,
  Edit,
  TrendingUp,
  AlertTriangle,
  Image as ImageIcon,
  Percent,
  Receipt,
  CheckCircle2,
  Star,
  ArrowRightLeft,
  Box,
  ClipboardList,
  PlusCircle,
  RefreshCw,
  DollarSign,
  Undo2,
  Shuffle,
  Layers,
  Tag,
  Building2,
  Sparkles,
  Briefcase,
  Gift,
  Award,
  UserCheck,
  UserX,
  LogOut,
  FileSignature,
  TrendingDown,
  CalendarRange,
  ShieldCheck as ShieldCheckIcon,
  BadgeDollarSign,
  GitBranch,
  FileSearch,
  Hash,
  HelpCircle,
  LineChart,
  AreaChart,
  Building,
  User,
  Sliders,
  CheckCircle,
  Smartphone,
} from "lucide-react";

export const OPERATIONAL_ITEMS = [
  {
    id: "pos",
    label: "نقاط البيع",
    icon: LayoutGrid,
    color: "bg-orange-500",
    features: [{ id: "pos_screen", label: "شاشة المبيعات", icon: LayoutGrid }],
    settings: [
      { id: "products", label: "إدارة الأقسام والمنتجات", icon: Settings },
      { id: "pos-settings", label: "إعدادات نقطة البيع المتقدمة", icon: Sliders },
    ],
    reports: [
      { id: "pos_sales_report", label: "تقارير عمليات البيع", icon: FileText },
      { id: "pos_dashboard_report", label: "لوحة مؤشرات POS والكاشير", icon: BarChart3 },
    ],
  },
  {
    id: "web-orders",
    label: "طلبات الأون لاين",
    icon: Target,
    color: "bg-blue-500",
    features: [
      { id: "list", label: "الطلبات الجديدة", icon: Target },
      { id: "archive", label: "أرشيف الطلبات", icon: FileText },
    ],
    settings: [],
    reports: [
      { id: "web_orders_report", label: "تقارير طلبات السايت", icon: FileText },
    ],
  },
  {
    id: "tables",
    label: "إدارة الطاولات",
    icon: Table2,
    color: "bg-emerald-500",
    features: [
      { id: "floor_plan", label: "حالة الطاولات", icon: Table2 },
      { id: "reservations", label: "حجوزات الصالة", icon: Calendar },
    ],
    settings: [],
    reports: [
      { id: "tables_report", label: "تقارير الطاولات", icon: FileText },
    ],
  },
  {
    id: "kitchen",
    label: "طلبات المطبخ",
    icon: ChefHat,
    color: "bg-teal-500",
    features: [
      { id: "screen", label: "شاشة المطبخ", icon: ChefHat },
      { id: "recipes", label: "الوصفات والمقادير", icon: FileText },
    ],
    settings: [],
    reports: [
      { id: "kitchen_report", label: "تقارير طلبات المطبخ", icon: FileText },
    ],
  },
  {
    id: "service",
    label: "فريق الكول سنتر",
    icon: UserCircle,
    color: "bg-cyan-500",
    features: [
      { id: "calls", label: "سجل مكالمات نقطة البيع", icon: UtensilsCrossed },
      { id: "new_customer", label: "إضافة عميل", icon: UserPlus },
    ],
    settings: [],
    reports: [
      {
        id: "call_center_report",
        label: "تقارير فريق الكول سنتر",
        icon: FileText,
      },
    ],
  },
  {
    id: "reservations",
    label: "الحجوزات",
    icon: Calendar,
    color: "bg-amber-500",
    features: [
      { id: "book", label: "حجز طاولة جديد", icon: Calendar },
      { id: "calendar", label: "أجندة الحجوزات", icon: Clock },
    ],
    settings: [],
    reports: [
      { id: "reservations_report", label: "تقارير الحجوزات", icon: FileText },
    ],
  },
  {
    id: "branch-reports",
    label: "تقارير الفروع",
    icon: Package,
    color: "bg-purple-500",
    features: [],
    settings: [],
    reports: [
      { id: "sales", label: "تقارير المبيعات", icon: BarChart3 },
      { id: "inventory", label: "تقارير حركة المخزن", icon: Warehouse },
    ],
  },
  {
    id: "delivery",
    label: "خدمة التوصيل",
    icon: Truck,
    color: "bg-pink-500",
    features: [
      { id: "active", label: "شحنات قيد التوصيل", icon: Truck },
      { id: "drivers", label: "قائمة السائقين", icon: Users },
    ],
    settings: [
      { id: "delivery-settings", label: "إعدادات الدليفري", icon: Truck },
    ],
    reports: [
      { id: "delivery_report", label: "تقارير خدمات التوصيل", icon: FileText },
    ],
  },
  {
    id: "customers",
    label: "قاعدة العملاء",
    icon: Users,
    color: "bg-indigo-500",
    features: [
      { id: "list", label: "قائمة العملاء", icon: Users },
      { id: "loyalty", label: "نقاط الولاء والخصومات", icon: Wallet },
    ],
    settings: [],
    reports: [
      { id: "customers_report", label: "تقارير العملاء", icon: FileText },
    ],
  },
  {
    id: "ai-chef",
    label: "مساعد الشيف الذكي",
    icon: Target,
    color: "bg-rose-500",
    features: [
      { id: "generate", label: "ابتكار وصفة ذكية", icon: Target },
      { id: "assistant", label: "مستشار الذكاء الاصطناعي", icon: ShieldCheck },
    ],
    settings: [],
    reports: [],
  },
  {
    id: "warehouses",
    label: "المخازن",
    icon: Warehouse,
    color: "bg-orange-500",
    features: [
      { id: "ingredients", label: "إدارة الأصناف", icon: Package },
      { id: "stock", label: "أرصدة الأصناف", icon: Box },
      { id: "transactions", label: "الحركات المخزنية", icon: ArrowRightLeft },
      { id: "goods_receipts", label: "سندات الاستلام (GRN & QC)", icon: ShieldCheck },
      { id: "material_requests", label: "طلبات وصرف المواد", icon: FileText },
      { id: "transfers", label: "التحويل بين المخازن", icon: Truck },
      { id: "count", label: "الجرد", icon: Calculator },
      { id: "adjustments", label: "التسويات", icon: Edit },
      { id: "damaged", label: "الهالك والتالف", icon: AlertTriangle },
      { id: "reserved", label: "المخزون المحجوز", icon: Lock },
      { id: "barcode", label: "الباركود", icon: Package },
      { id: "main", label: "إدارة المخازن", icon: Warehouse },
      { id: "locations", label: "مواقع التخزين والأرفف", icon: FolderTree },
    ],
    settings: [
      { id: "settings", label: "الإعدادات العامة", icon: Settings },
      { id: "warehouse_types", label: "أنواع المخازن", icon: Building2 },
      { id: "transaction_types", label: "أنواع الحركات", icon: ArrowRightLeft },
      { id: "transaction_reasons", label: "أسباب الحركات", icon: FileText },
    ],
    reports: [
      { id: "stock_balance", label: "رصيد المخزون", icon: Box },
      { id: "low_stock", label: "الأصناف منخفضة الكمية", icon: AlertTriangle },
      { id: "transactions_report", label: "تقارير الحركات", icon: ArrowRightLeft },
      { id: "transfers_report", label: "تقارير التحويلات", icon: Truck },
      { id: "valuation", label: "تقييم المخزون", icon: DollarSign },
      { id: "damaged_report", label: "تقرير الهالك", icon: AlertTriangle },
      { id: "item_ledger", label: "كارت الصنف والحركة التفصيلية", icon: BookOpen },
      { id: "aging_report", label: "تقرير أعمار المخزون", icon: Clock },
      { id: "slow_moving", label: "الأصناف الراكدة", icon: History },
      { id: "abc", label: "تحليل ABC (باريتو)", icon: BarChart3 },
      { id: "suppliers_report", label: "تقرير الموردين", icon: Users },
    ],
  },
  {
    id: "printers",
    label: "الطابعات",
    icon: Printer,
    color: "bg-slate-600",
    features: [{ id: "manage", label: "إعداد الطابعات", icon: Printer }],
    settings: [],
    reports: [{ id: "logs", label: "سجلات الطباعة", icon: FileText }],
  },
  {
    id: "complaints",
    label: "الشكاوي",
    icon: MessageSquareWarning,
    color: "bg-red-500",
    features: [
      { id: "active", label: "الشكاوي الواردة", icon: MessageSquareWarning },
      { id: "archive", label: "أرشيف الشكاوي والحلول", icon: FileText },
    ],
    settings: [],
    reports: [
      { id: "complaints_report", label: "تقارير الشكاوي", icon: FileText },
    ],
  },
  {
    id: "approvals",
    label: "الموافقات",
    icon: CheckCircle,
    color: "bg-violet-500",
    features: [
      { id: "pending", label: "طلبات الموافقة", icon: CheckCircle },
      { id: "history", label: "سجل الموافقات", icon: History },
      { id: "settings", label: "إعدادات الموافقات", icon: Sliders },
    ],
    settings: [],
    reports: [],
  },
];

export const ADMIN_ITEMS = [
  {
    id: "hr-presentation",
    label: "عرض المنظومة (HR Presentation)",
    icon: ShieldCheck,
    color: "bg-blue-600",
    features: [],
    settings: [],
    reports: []
  },
  {
    id: "hotel",
    label: "إدارة الفنادق",
    icon: Building2,
    color: "bg-teal-600",
    features: [
      { id: "dashboard", label: "لوحة تحكم الفندق", icon: BarChart3 },
      { id: "properties", label: "الفنادق والعقارات", icon: Building2 },
      { id: "room_types", label: "أنواع الغرف", icon: Layers },
      { id: "rooms", label: "إدارة الغرف", icon: Box },
      { id: "front_desk", label: "مكتب الاستقبال ومخطط الغرف", icon: Calendar },
      { id: "reservations", label: "الحجوزات الفندقية", icon: CalendarDays },
      { id: "guests", label: "سجل النزلاء", icon: Users },
      { id: "housekeeping", label: "النظافة والخدمات", icon: RefreshCw },
      { id: "room_service", label: "خدمة الغرف والتحميل", icon: ShoppingCart },
      { id: "maintenance", label: "صيانة الغرف", icon: Wrench },
      { id: "billing", label: "الفواتير والمدفوعات", icon: DollarSign },
      { id: "inventory", label: "مخزون مستلزمات الفندق", icon: Warehouse },
      { id: "ai_insights", label: "الذكاء الاصطناعي والتوقعات", icon: Sparkles }
    ],
    settings: [
      { id: "hotel_settings", label: "إعدادات السياسات والضرائب", icon: Settings }
    ],
    reports: [
      { id: "hotel_reports", label: "تقارير الإشغال والإيرادات و KPIs", icon: FileText }
    ]
  },
  {
    id: "sales",
    label: "المبيعات والتوريد",
    icon: ShoppingCart,
    color: "bg-indigo-600",
    features: [
      { id: "quotations", label: "عروض الأسعار", icon: FileText },
      { id: "orders", label: "أوامر البيع والتنفيذ", icon: ShoppingCart },
      { id: "deliveries", label: "أذونات التسليم والمخازن", icon: Truck },
      { id: "invoices", label: "فاتورة البيع والضريبة", icon: DollarSign },
      { id: "returns", label: "مرتجعات البيع والقيود", icon: Undo2 },
      { id: "reservations", label: "حجوزات المنتجات", icon: Clock },
      { id: "reps", label: "المناديب والعمولات", icon: Users },
      { id: "pricelists", label: "قوائم الأسعار المتعددة", icon: Percent },
      { id: "contracts", label: "إدارة العقود والتوريد", icon: FileSignature }
    ],
    settings: [
      { id: "products", label: "إدارة منتجات المبيعات", icon: Package },
      { id: "pricelists", label: "قوائم الأسعار المتعددة", icon: Percent },
      { id: "sales_settings", label: "إعدادات وسياسات المبيعات", icon: Settings },
    ],
    reports: [
      { id: "sales_dashboard", label: "مؤشرات المبيعات والربحية", icon: BarChart3 },
      { id: "report_sales_summary", label: "ملخص المبيعات الشامل والأداء", icon: FileText },
      { id: "report_sales_profitability", label: "تقرير ربحية وهوامش المبيعات (COGS)", icon: TrendingUp },
      { id: "report_sales_items", label: "تقرير مبيعات الأصناف الأكثر مبيعاً", icon: Package },
      { id: "report_sales_orders", label: "تقرير أوامر البيع وحالات التنفيذ", icon: ShoppingCart },
      { id: "report_sales_deliveries", label: "تقرير أذونات التسليم والصرف المخزني", icon: Truck },
      { id: "report_sales_invoices", label: "تقرير فواتير البيع وضريبة القيمة المضافة", icon: DollarSign },
      { id: "report_sales_returns", label: "تقرير مرتجعات المبيعات والقيود العكسية", icon: Undo2 },
      { id: "report_sales_reps", label: "تقرير أداء المناديب وتارجت العمولات", icon: Users },
      { id: "report_sales_customers", label: "تقرير مسحوبات وحسابات مديونية العملاء", icon: UserCheck },
      { id: "report_sales_reservations", label: "تقرير حجوزات المنتجات بالمستودعات", icon: Clock },
      { id: "report_sales_quotations", label: "تقرير عروض الأسعار ومعدلات التحويل", icon: ArrowRightLeft },
      { id: "report_sales_contracts", label: "تقرير عقود التوريد والاتفاقيات السارية", icon: FileSignature },
      { id: "report_sales_branches", label: "تقرير المبيعات حسب الفروع ونقاط البيع", icon: Building2 },
      { id: "report_sales_daily", label: "تقرير حركة المبيعات والتحصيلات اليومية", icon: Calendar },
    ]
  },
  {
    id: "production",
    label: "الإنتاج والتصنيع",
    icon: Factory,
    color: "bg-amber-600",
    features: [
      { id: "indicators", label: "لوحة المؤشرات", icon: Activity },
      { id: "products", label: "إدارة المنتجات والأصناف", icon: Package },
      { id: "bom", label: "وصفات التصنيع (BOM)", icon: FileText },
      { id: "work_centers", label: "مراكز العمل والتوجيه", icon: Settings },
      { id: "mrp", label: "تخطيط الاحتياجات (MRP)", icon: Calendar },
      { id: "production_orders", label: "أوامر الإنتاج", icon: FileText },
      { id: "shop_floor", label: "التحكم أرض المصنع", icon: Zap },
      { id: "quality", label: "مراقبة الجودة", icon: ShieldCheck },
      { id: "maintenance", label: "إدارة الصيانة", icon: Wrench },
      { id: "costs", label: "حساب التكاليف", icon: Calculator },
    ],
    settings: [],
    reports: [
      // التقارير التشغيلية
      { id: "report_op_summary", label: "ملخص التكاليف", icon: FileText },
      { id: "report_op_daily", label: "تقرير التكاليف اليومية", icon: Calendar },
      { id: "report_op_weekly", label: "تقرير التكاليف الأسبوعية", icon: Calendar },
      { id: "report_op_monthly", label: "تقرير التكاليف الشهرية", icon: Calendar },
      { id: "report_op_yearly", label: "تقرير التكاليف السنوية", icon: Calendar },
      { id: "report_op_transactions", label: "تقرير عمليات التكاليف", icon: FileText },
      { id: "report_op_approved", label: "تقرير العمليات المعتمدة", icon: CheckCircle2 },
      { id: "report_op_pending", label: "تقرير العمليات المعلقة", icon: Clock },

      // تقارير مراكز التكلفة
      { id: "report_cc_all", label: "تقرير كل مركز تكلفة", icon: Layers },
      { id: "report_cc_compare", label: "مقارنة مراكز التكلفة", icon: ArrowRightLeft },
      { id: "report_cc_highest", label: "أعلى مركز تكلفة", icon: TrendingUp },
      { id: "report_cc_lowest", label: "أقل مركز تكلفة", icon: TrendingDown },
      { id: "report_cc_dept", label: "تكلفة كل إدارة", icon: Building2 },

      // تقارير عناصر التكلفة
      { id: "report_item_all", label: "تقرير عناصر التكلفة", icon: Tag },
      { id: "report_item_expense", label: "تقرير المصروفات حسب العنصر", icon: FileText },
      { id: "report_item_compare", label: "مقارنة عناصر التكلفة", icon: ArrowRightLeft },
      { id: "report_item_highest", label: "أعلى عنصر تكلفة", icon: TrendingUp },

      // تقارير المنتجات
      { id: "report_prod_cost", label: "تكلفة المنتج", icon: Package },
      { id: "report_prod_unit", label: "تكلفة الوحدة", icon: Hash },
      { id: "report_prod_margin", label: "هامش الربح", icon: DollarSign },
      { id: "report_prod_material", label: "تكلفة المواد", icon: Layers },
      { id: "report_prod_operation", label: "تكلفة التشغيل", icon: Activity },

      // تقارير المشاريع
      { id: "report_proj_cost", label: "تكلفة المشروع", icon: Briefcase },
      { id: "report_proj_profit", label: "الربحية", icon: DollarSign },
      { id: "report_proj_progress", label: "نسبة الإنجاز", icon: Percent },
      { id: "report_proj_compare", label: "مقارنة المشاريع", icon: ArrowRightLeft },

      // تقارير الفروع
      { id: "report_branch_cost", label: "تكلفة الفروع", icon: Building },
      { id: "report_branch_compare", label: "مقارنة الفروع", icon: ArrowRightLeft },
      { id: "report_branch_profit", label: "ربحية الفروع", icon: DollarSign },

      // تقارير الموظفين
      { id: "report_emp_cost", label: "تكلفة الموظف", icon: User },
      { id: "report_emp_dept", label: "تكلفة القسم", icon: Users },
      { id: "report_emp_admin", label: "تكلفة الإدارة", icon: Building2 },
      { id: "report_emp_labor", label: "تكلفة العمالة", icon: Users },

      // تقارير الميزانيات
      { id: "report_budget_actual", label: "Budget vs Actual", icon: BookOpen },
      { id: "report_budget_consumption", label: "نسبة الاستهلاك", icon: Percent },
      { id: "report_budget_remaining", label: "المتبقي من الميزانية", icon: Wallet },
      { id: "report_budget_exceeded", label: "تجاوز الميزانية", icon: AlertTriangle },

      // تقارير الانحراف
      { id: "report_var_standard", label: "Standard vs Actual", icon: ArrowRightLeft },
      { id: "report_var_ratio", label: "نسبة الانحراف", icon: Percent },
      { id: "report_var_reasons", label: "أسباب الانحراف", icon: HelpCircle },
      { id: "report_var_highest", label: "أعلى الانحرافات", icon: TrendingUp },

      // التقارير التحليلية
      { id: "report_ana_product", label: "تحليل التكاليف حسب المنتج", icon: PieChart },
      { id: "report_ana_branch", label: "تحليل التكاليف حسب الفرع", icon: PieChart },
      { id: "report_ana_project", label: "تحليل التكاليف حسب المشروع", icon: PieChart },
      { id: "report_ana_supplier", label: "تحليل التكاليف حسب المورد", icon: PieChart },
      { id: "report_ana_customer", label: "تحليل التكاليف حسب العميل", icon: PieChart },
      { id: "report_ana_center", label: "تحليل التكاليف حسب مركز التكلفة", icon: PieChart },
      { id: "report_ana_item", label: "تحليل التكاليف حسب عنصر التكلفة", icon: PieChart },
      { id: "report_ana_period", label: "تحليل التكاليف حسب الفترة الزمنية", icon: LineChart },

      // الرسوم البيانية
      { id: "report_chart_trend", label: "Cost Trend", icon: TrendingUp },
      { id: "report_chart_monthly", label: "Monthly Cost Analysis", icon: BarChart3 },
      { id: "report_chart_branch", label: "Branch Cost Analysis", icon: BarChart3 },
      { id: "report_chart_product", label: "Product Cost Analysis", icon: BarChart3 },
      { id: "report_chart_center", label: "Cost Center Analysis", icon: BarChart3 },
      { id: "report_chart_budget", label: "Budget Analysis", icon: AreaChart },
      { id: "report_chart_variance", label: "Variance Analysis", icon: BarChart3 },
      { id: "report_chart_top_centers", label: "Top Cost Centers", icon: BarChart3 },
      { id: "report_chart_top_expenses", label: "Top Expense Categories", icon: BarChart3 },
      { id: "report_chart_top_products", label: "Top Products by Cost", icon: BarChart3 },
      { id: "report_chart_period_compare", label: "مقارنة الفترات الزمنية", icon: LineChart },
    ],
  },
  {
    id: "hr",
    label: "الموارد البشرية",
    icon: Users,
    color: "bg-purple-500",
    features: [
      { id: "professional", label: "لوحة HR الاحترافية", icon: ShieldCheck },
      { id: "recruitment", label: "التوظيف", icon: UserPlus },
      { id: "employee_basic_info", label: "بيانات الموظف الأساسية", icon: UserCheck },
      { id: "employees", label: "الموظفون", icon: Users },
      { id: "documents", label: "ملفات الموظفين", icon: FileText },
      { id: "custody", label: "عهد الموظفين", icon: Package },
      { id: "payroll_elements", label: "عناصر الراتب", icon: Calculator },
      { id: "annual_increases", label: "موافقات الزيادة السنوية", icon: TrendingUp },
      { id: "production_bonuses", label: "حوافز الإنتاج والمصنع", icon: Zap },
      { id: "leaves", label: "إدارة الإجازات", icon: CalendarDays },
      { id: "portal_requests", label: "موافقات التطبيب والمذكرات", icon: CheckCircle2 },
      { id: "evaluations", label: "تقييم الموظفين", icon: Star },
      {
        id: "award_penalties",
        label: "إدارة الجزاءات",
        icon: MessageSquareWarning,
      },
      {
        id: "employee_warnings",
        label: "محاضر إنذارات الموظفين",
        icon: AlertTriangle,
      },
      { id: "bulk_actions", label: "الإجراءات الجماعية", icon: Layers },
      { id: "clearance", label: "إخلاء الطرف والتقارير", icon: CheckCircle2 },
    ],
    settings: [
      { id: "branches", label: "إدارة الفروع", icon: MapPin },
      { id: "departments", label: "إدارة الأقسام", icon: Target },
      { id: "penalties", label: "لائحة الجزاءات", icon: ShieldAlert },
      { id: "leave_settings", label: "لائحة الإجازات", icon: FileCog },
      { id: "shifts", label: "إدارة الورديات", icon: Clock },
      { id: "hr_settings", label: "إعدادات الموارد البشرية", icon: Settings },
    ],
    reports: [
      { id: "comprehensive_report", label: "التقرير الشامل", icon: FileText },
      { id: "employee_warnings", label: "سجل ومحاضر إنذارات الموظفين", icon: AlertTriangle },
      { id: "hr_report", label: "تقرير الموظفين النشطين", icon: Users },
      { id: "hr_bonuses_report", label: "تقارير المكافآت والبدلات", icon: Gift },
      { id: "hr_incentives_report", label: "تقارير الحوافز الشهرية", icon: Zap },
      { id: "hr_production_bonuses_report", label: "تقارير مكافآت الإنتاج والتصنيع", icon: Briefcase },
      { id: "hr_evaluations_report", label: "تقارير تقييم الأداء والإنتاجية", icon: Star },
      { id: "hr_clearance_report", label: "سجل وتقارير إخلاء الطرف", icon: CheckCircle2 },
      { id: "hr_detailed_report", label: "تقرير الموظفين المفصل الشامل", icon: FileSpreadsheet },
    ],
  },
  {
    id: "branches",
    label: "إدارة الفروع",
    icon: MapPin,
    color: "bg-emerald-500",
    features: [{ id: "main", label: "لوحة التحكم", icon: LayoutGrid }],
    settings: [],
    reports: [
      { id: "branches_report", label: "تقارير الفروع", icon: FileText },
    ],
  },
  {
    id: "banks",
    label: "إدارة البنوك",
    icon: Landmark,
    color: "bg-indigo-600",
    features: [
      { id: "accounts", label: "الحسابات البنكية", icon: Landmark },
      { id: "transactions", label: "الحركات البنكية", icon: ArrowRightLeft },
      { id: "transfers", label: "التحويلات بين الحسابات", icon: ArrowRightLeft },
      { id: "reconciliation", label: "التسوية البنكية", icon: Scale },
    ],
    settings: [
      { id: "bank_settings", label: "إعدادات البنوك", icon: Settings },
      { id: "bank_accounting", label: "ربط البنوك بالمحاسبة", icon: GitBranch },
    ],
    reports: [
      { id: "bank_balances", label: "تقرير أرصدة البنوك", icon: Wallet },
      { id: "bank_transactions", label: "كشف حركات البنك", icon: FileText },
      { id: "bank_reconciliation", label: "تقرير التسوية البنكية", icon: CheckCircle2 },
      { id: "bank_flow", label: "تقرير التدفق النقدي البنكي", icon: TrendingUp },
    ],
  },
  {
    id: "real-estate",
    label: "إدارة العقارات",
    icon: Building2,
    color: "bg-emerald-600",
    features: [
      { id: "properties", label: "العقارات والممتلكات", icon: Building2 },
      { id: "leases", label: "الإيجارات والعقود", icon: FileText },
      { id: "expenses", label: "مصروفات العقارات", icon: Wallet },
      { id: "collections", label: "تحصيل الإيجارات", icon: DollarSign },
      { id: "maintenance", label: "صيانة العقارات", icon: Wrench },
    ],
    settings: [
      { id: "realestate_settings", label: "إعدادات العقارات", icon: Settings },
      { id: "realestate_accounting", label: "ربط العقارات بالمحاسبة", icon: GitBranch },
      { id: "realestate_branches", label: "ربط العقارات بالفروع", icon: MapPin },
    ],
    reports: [
      { id: "realestate_register", label: "سجل العقارات", icon: FileText },
      { id: "realestate_rent", label: "تقرير الإيجارات والتحصيل", icon: Wallet },
      { id: "realestate_expenses", label: "تقرير مصروفات العقارات", icon: Receipt },
      { id: "realestate_occupancy", label: "تقرير الإشغال", icon: BarChart3 },
      { id: "realestate_value", label: "تقرير قيم العقارات", icon: TrendingUp },
    ],
  },
  {
    id: "safes",
    label: "إدارة الخزائن",
    icon: Wallet,
    color: "bg-indigo-500",
    features: [
      { id: "accounts", label: "الخزائن المتوفرة", icon: Wallet },
      { id: "transactions", label: "حركات الخزينة", icon: History },
      { id: "transfers", label: "التحويلات المالية البينية", icon: ArrowRightLeft },
      { id: "closings", label: "تقفيل وتسويات الخزينة", icon: ShieldCheck },
      { id: "custodies", label: "حركة العهد والأمانات", icon: Users },
      { id: "audit", label: "سجل المتابعة والتعديلات", icon: History },
      { id: "settings", label: "إعدادات الرقابة والنظام", icon: Settings },
    ],
    settings: [
      { id: "bank_accounts", label: "حسابات الخزائن والبنوك", icon: Landmark },
    ],
    reports: [
      { id: "treasury_detailed", label: "تقرير الحركات التفصيلي", icon: History },
      { id: "treasury_transfers", label: "تقرير التحويلات البينية", icon: ArrowRightLeft },
      { id: "treasury_closings", label: "تقرير تقفيل وتسويات الخزائن", icon: ShieldCheck },
      { id: "treasury_custodies", label: "تقرير حركة العهد والأمانات", icon: Users },
    ],
  },
  {
    id: "customer-accounts",
    label: "حسابات العملاء",
    icon: UserPlus,
    color: "bg-blue-500",
    features: [{ id: "main", label: "العملاء", icon: Users }],
    settings: [],
    reports: [
      { id: "accounts_report", label: "تقارير الحسابات", icon: FileText },
    ],
  },
  {
    id: "suppliers",
    label: "ج. الموردين",
    icon: TruckIcon,
    color: "bg-orange-500",
    features: [{ id: "main", label: "الموردين", icon: TruckIcon }],
    settings: [],
    reports: [
      { id: "suppliers_report", label: "تقارير الموردين", icon: FileText },
      { id: "suppliers_detailed_report", label: "تقرير تفصيلي لحسابات وبنود الموردين والفواتير", icon: FileSpreadsheet },
    ],
  },
  {
    id: "salaries",
    label: "المرتبات",
    icon: Package,
    color: "bg-emerald-500",
    features: [
      { id: "approved", label: "كشوف الرواتب المعتمدة", icon: Wallet },
      { id: "advances", label: "إدارة السلف والعهد", icon: BookOpen },
      { id: "bonuses", label: "المكافآت والبدلات", icon: PieChart },
      {
        id: "penalties",
        label: "الخصومات والاستقطاعات",
        icon: MessageSquareWarning,
      },
    ],
    settings: [
      { id: "settings", label: "إعدادات البنود", icon: Settings },
      { id: "month-lock", label: "قفل وإغلاق الشهور المالي", icon: Lock },
    ],
    reports: [
      { id: "salary_reports", label: "تقارير الرواتب والأجور", icon: FileText },
    ],
  },
  {
    id: "general-accounts",
    label: "حسابات عامة",
    icon: Calculator,
    color: "bg-amber-500",
    features: [
      { id: "accounts", label: "شجرة الحسابات", icon: FolderTree },
      { id: "journal", label: "القيود اليومية", icon: BookOpen },
      { id: "ledger", label: "الأستاذ العام", icon: History },
      { id: "trial_balance", label: "ميزان المراجعة", icon: BarChart3 },
      { id: "cost_centers", label: "مراكز التكلفة", icon: PieChart },
      { id: "customers_suppliers", label: "العملاء والموردين", icon: Users },
      { id: "vouchers", label: "سندات القبض والصرف", icon: FileText },
      { id: "bank_reconciliation", label: "البنك والتسوية البنكية", icon: Scale },
      { id: "fixed_assets", label: "الأصول الثابتة", icon: Percent },
      { id: "taxes", label: "الضرائب", icon: Receipt },
    ],
    settings: [
      { id: "erp_fiscal_years", label: "السنوات المالية والفترات", icon: CalendarRange },
      { id: "erp_account_config", label: "ربط الحسابات التلقائي", icon: GitBranch },
      { id: "erp_budgets", label: "إدارة الموازنات", icon: BadgeDollarSign },
      { id: "erp_audit_logs", label: "سجل المراجعة", icon: FileSearch },
    ],
    reports: [
      { id: "income_statement", label: "قائمة الدخل", icon: Clock },
      { id: "balance_sheet", label: "الميزانية العمومية", icon: FileText },
      { id: "accounts_report", label: "طبيعة الحسابات والقيود", icon: FileText },
      { id: "accounting_reports", label: "تقارير المحاسبيه", icon: FileText },
    ],
  },
  {
    id: "database",
    label: "قاعدة البيانات",
    icon: Database,
    color: "bg-indigo-500",
    features: [{ id: "main", label: "التحكم", icon: Database }],
    settings: [],
    reports: [{ id: "backup_logs", label: "سجلات العمليات", icon: FileText }],
  },
  {
    id: "costs",
    label: "التكاليف",
    icon: BarChart3,
    color: "bg-cyan-500",
    features: [
      { id: "dashboard", label: "لوحة التحكم", icon: LayoutGrid },
      { id: "operating_costs", label: "التكاليف التشغيلية", icon: Wallet },
      { id: "budget", label: "الموازنة التقديرية", icon: Calendar },
      { id: "centers", label: "مراكز التكلفة", icon: PieChart },
      { id: "items", label: "بنود التكاليف والمصاريف", icon: FileText },
      { id: "allocation", label: "توزيع وتحميل التكاليف", icon: Shuffle },
      { id: "standard_costing", label: "التكاليف المعيارية والانحرافات", icon: Percent },
      { id: "product_costing", label: "حساب تكلفة المنتج", icon: Calculator },
      { id: "form", label: "إضافة تكلفة جديدة", icon: PlusCircle },
    ],
    settings: [
      { id: "settings_general", label: "التهيئة العامة والربط", icon: Settings },
      { id: "settings_rules", label: "قواعد وهياكل التكاليف", icon: Shuffle },
      { id: "settings_budgets", label: "الموازنات والاعتمادات", icon: BookOpen },
      { id: "settings_permissions", label: "صلاحيات وأمان المستخدمين", icon: UserCheck },
    ],
    reports: [
      { id: "report_overview", label: "التحليل العام", icon: BarChart3 },
      { id: "report_centers", label: "أداء مراكز التكلفة", icon: Layers },
      { id: "report_items", label: "تحليل بنود الصرف", icon: Tag },
      { id: "report_branches", label: "توزيع الفروع والأقسام", icon: Building2 },
      { id: "report_log", label: "سجل الحركة التفصيلية", icon: FileText },
      { id: "report_projects", label: "تكاليف المشاريع", icon: Briefcase },
      { id: "report_employees", label: "تكاليف الموظفين والعمالة", icon: UserCheck },
      { id: "report_budget_actual", label: "الموازنة التقديرية vs الفعلي", icon: BookOpen },
      { id: "report_activity_logs", label: "سجل مراجعة الحركات", icon: History },
    ],
  },
  {
    id: "central-reports",
    label: "التقارير المركزية",
    icon: FileText,
    color: "bg-indigo-600",
    features: [],
    settings: [],
    reports: [
      { id: "branches", label: "تقارير المبيعات والفروع", icon: BarChart3 },
      { id: "hr", label: "تقرير الموظفين والأساسيات", icon: Users },
      { id: "hr_bonuses", label: "تقرير المكافآت والبدلات", icon: Gift },
      { id: "hr_incentives", label: "تقرير الحوافز الشهرية", icon: Zap },
      { id: "hr_production_bonuses", label: "تقرير مكافآت الإنتاج والتصنيع", icon: Briefcase },
      { id: "hr_evaluations", label: "تقرير تقييم الأداء والإنتاجية", icon: Star },
      { id: "hr_clearance", label: "سجل وتقارير إخلاء الطرف", icon: CheckCircle2 },
      { id: "hr_detailed_report", label: "تقرير الموظفين المفصل الشامل", icon: FileSpreadsheet },
      { id: "attendance_summary", label: "كشف تقرير الحضور والانصراف العام", icon: Clock },
      { id: "fingerprint_logs_report", label: "تقرير سجلات وحركات البصمة", icon: FileText },
      { id: "tardiness_report", label: "تقرير تأخيرات الموظفين والخصومات", icon: AlertTriangle },
      { id: "absence_report", label: "تقرير الغياب والغياب بدون إذن", icon: UserX },
      { id: "overtime_report", label: "تقرير الساعات الإضافية (أوفرتايم)", icon: Zap },
      { id: "early_departure_report", label: "تقرير الانصراف المبكر", icon: LogOut },
      { id: "salaries", label: "تقارير الرواتب والأجور", icon: Calculator },
      { id: "safes", label: "تقارير الخزنة الرئيسية والسرية", icon: Wallet },
      {
        id: "warehouse_transactions",
        label: "تقارير حركات المخازن",
        icon: Warehouse,
      },
      {
        id: "general_accounts",
        label: "طبيعة الحسابات والقيود",
        icon: FileText,
      },
    ],
  },
  {
    id: "purchases",
    label: "المشتريات",
    icon: ShoppingCart,
    color: "bg-emerald-500",
    features: [
      { id: "requests", label: "طلبات الشراء", icon: FileText },
      { id: "orders", label: "أوامر الشراء", icon: ShoppingCart },
      { id: "receipts", label: "استلام المشتريات", icon: FileText },
      { id: "invoices", label: "فواتير المشتريات", icon: FileText },
      { id: "returns", label: "مرتجعات المشتريات", icon: RefreshCw },
      { id: "expenses", label: "مصاريف إضافية", icon: DollarSign },
      { id: "quotations", label: "عروض أسعار", icon: FileText },
    ],
    settings: [
      { id: "purchase_einvoice", label: "إعدادات الفاتورة الإلكترونية", icon: Receipt },
    ],
    reports: [
      { id: "purchase_summary", label: "ملخص المشتريات الشامل", icon: BarChart3 },
      { id: "purchase_orders_report", label: "تقرير أوامر الشراء", icon: ShoppingCart },
      { id: "purchase_requests_report", label: "تقرير طلبات الشراء", icon: FileText },
      { id: "purchase_quotations_report", label: "تقرير عروض الأسعار والمقارنة", icon: FileText },
      { id: "purchase_receipts_report", label: "تقرير الاستلام والفحص GRN", icon: Package },
      { id: "purchase_invoices_report", label: "تقرير فواتير المشتريات", icon: Receipt },
      { id: "purchase_returns_report", label: "تقرير مرتجعات المشتريات", icon: RefreshCw },
      { id: "purchase_expenses_report", label: "تقرير المصاريف والتكاليف الإضافية", icon: DollarSign },
      { id: "purchase_suppliers_report", label: "تقرير مشتريات الموردين", icon: Users },
      { id: "purchase_items_report", label: "تقرير الأصناف والكميات المشتراة", icon: Box },
      { id: "purchase_prices_report", label: "تقرير أسعار الشراء", icon: TrendingUp },
      { id: "purchase_payments_report", label: "تقرير مدفوعات الموردين", icon: Wallet },
      { id: "purchase_outstanding_report", label: "تقرير مستحقات الموردين وأعمار الديون", icon: Clock },
      { id: "purchase_taxes_report", label: "تقرير ضرائب المشتريات", icon: Receipt },
      { id: "purchase_matching_report", label: "تقرير المطابقة الثلاثية 3-Way Match", icon: CheckCircle },
      { id: "purchase_warehouse_report", label: "تقرير المشتريات حسب المخزن", icon: Warehouse },
      { id: "purchase_cost_centers_report", label: "تقرير المشتريات حسب مراكز التكلفة", icon: Target },
      { id: "purchase_monthly_report", label: "التقرير الشهري والاتجاهات", icon: Calendar },
      { id: "purchase_workflow_report", label: "تقرير دورة المشتريات ومراحلها", icon: GitBranch },
    ],
  },
  {
    id: "approvals",
    label: "الموافقات",
    icon: CheckCircle,
    color: "bg-violet-500",
    features: [
      { id: "pending", label: "طلبات الموافقة", icon: CheckCircle },
      { id: "history", label: "سجل الموافقات", icon: History },
      { id: "settings", label: "إعدادات الموافقات", icon: Sliders },
    ],
    settings: [],
    reports: [],
  },
  {
    id: "attendance",
    label: "الحضور",
    icon: Clock,
    color: "bg-rose-500",
    features: [
      { id: "main", label: "سجلات الحضور", icon: Clock },
      {
        id: "fingerprint-logs",
        label: "مراجعة وتعديل سجلات البصمة",
        icon: FileText,
      },
    ],
    settings: [
      {
        id: "fingerprint-settings",
        label: "إعدادات أجهزة بصمة الحضور",
        icon: ShieldCheck,
      },
    ],
    reports: [
      {
        id: "attendance_summary",
        label: "كشف تقرير الحضور والانصراف العام",
        icon: Clock,
      },
      {
        id: "fingerprint_logs_report",
        label: "تقرير سجلات وحركات البصمة",
        icon: FileText,
      },
      {
        id: "tardiness_report",
        label: "تقرير تأخيرات الموظفين والخصومات",
        icon: AlertTriangle,
      },
      {
        id: "absence_report",
        label: "تقرير الغياب والغياب بدون إذن",
        icon: UserX,
      },
      {
        id: "overtime_report",
        label: "تقرير الساعات الإضافية (أوفرتايم)",
        icon: Zap,
      },
      {
        id: "early_departure_report",
        label: "تقرير الانصراف المبكر",
        icon: LogOut,
      },
    ],
  },
  {
    id: "security",
    label: "السرية والتحكم",
    icon: ShieldCheck,
    color: "bg-orange-500",
    features: [
      { id: "users", label: "إدارة المستخدمين والصلاحيات", icon: Users },
      { id: "user-logs", label: "سجل حركات النظام والأمان", icon: History },
      {
        id: "backup",
        label: "النسخ الاحتياطي واستعادة البيانات",
        icon: Database,
      },
      {
        id: "mobile_app",
        label: "تطبيق موبايل الطاولات والمنيو",
        icon: Smartphone,
      },
    ],
    settings: [],
    reports: [
      {
        id: "modifications_report",
        label: "تقرير تعديلات وإلغاءات النظام",
        icon: FileText,
      },
    ],
  },
  {
    id: "exclusive",
    label: "الحصري",
    icon: BarChart3,
    color: "bg-blue-500",
    features: [],
    settings: [],
    reports: [{ id: "main", label: "التقارير", icon: BarChart3 }],
  },
  {
    id: "erp_core",
    label: "المنظومة الاحترافية ERP",
    icon: ShieldCheck,
    color:
      "bg-slate-900 border border-slate-700/60 shadow-lg shadow-cyan-500/10",
    features: [{ id: "main", label: "لوحة التحكم", icon: LayoutGrid }],
    settings: [],
    reports: [{ id: "erp_reports", label: "تقارير المنظومة", icon: BarChart3 }],
  },
  {
    id: "ai_developer",
    label: "مركز تطوير AI",
    icon: Bot,
    color: "bg-indigo-600 border border-indigo-500/40 shadow-lg shadow-indigo-500/20",
    features: [
      { id: "dashboard", label: "لوحة التحكم", icon: LayoutGrid },
      { id: "project_analysis", label: "تحليل المشروع", icon: FileText },
      { id: "bug_detector", label: "كاشف الأخطاء", icon: ShieldAlert },
      { id: "security_scanner", label: "فاحص الأمان", icon: ShieldCheck },
      { id: "performance_analyzer", label: "محلل الأداء", icon: Zap },
      { id: "database_optimizer", label: "تحسين القواعد", icon: Database },
      { id: "feature_generator", label: "مولد الميزات", icon: Zap },
      { id: "api_generator", label: "مولد APIs", icon: FileText },
      { id: "ui_generator", label: "مولد الواجهات", icon: LayoutGrid },
      { id: "doc_generator", label: "مولد التوثيق", icon: FileText },
      { id: "test_generator", label: "الاختبارات", icon: ShieldCheck },
      { id: "code_review", label: "مراجعة الكود", icon: CheckCircle2 },
      { id: "ai_chat", label: "مساعد AI Chat", icon: Users },
      { id: "sandbox", label: "بيئة Sandbox", icon: Database },
      { id: "audit_log", label: "سجل العمليات", icon: Clock },
    ],
    settings: [],
    reports: [],
  },
];
